// Seeded autocomplete source for the prescription composer's medicine name
// field. Static reference data -- no admin-editable requirement in CLAUDE.md,
// so a plain constant is sufficient (YAGNI: no backend endpoint needed).
export const GENERIC_MEDICINES: readonly string[] = [
  'Paracetamol',
  'Ibuprofen',
  'Cetirizine',
  'Levocetirizine',
  'Amoxicillin',
  'Azithromycin',
  'Pantoprazole',
  'Omeprazole',
  'Domperidone',
  'Ondansetron',
  'Metronidazole',
  'Ciprofloxacin',
  'Amlodipine',
  'Atenolol',
  'Losartan',
  'Metformin',
  'Glimepiride',
  'Atorvastatin',
  'Salbutamol',
  'Montelukast',
  'Hydrocortisone Cream',
  'Betamethasone Cream',
  'Clotrimazole Cream',
  'Diclofenac',
  'Aceclofenac',
  'Vitamin D3',
  'Vitamin B12',
  'Calcium Carbonate',
  'Iron + Folic Acid',
  'ORS Sachets',
  'Loperamide',
  'Ranitidine',
  'Sertraline',
  'Escitalopram',
  'Alprazolam',
  'Thyroxine',
  'Insulin (Regular)',
  'Insulin (NPH)',
  'Amoxiclav',
  'Doxycycline',
  'Prednisolone',
];
